######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 13 15:04:07 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lcln -lginac -lcycle -lfigure -L./


# Input
HEADERS += cycle.h figure.h library.hpp
SOURCES += cycle.cpp figure.cpp library.cpp main.cpp
