######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 18:28:29 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += library.hpp
SOURCES += library.cpp main.cpp
